### ISSUE TITLE
Sorry, this link has expired 

### ISSUE THREAD

**Issue by suirad-star** [abigpotostew/microcosmbot#2] opened 2024-02-11 12:41 UTC
After several attempts of "Connect New Wallet" and "Use Existing Wallets" with successful verification of the wallet addresses, I am getting the "Sorry, this link has expired" after selecting the unique invite link that is provided in the MicroCosmBot Telegram DM. I am unable to join the Bad Kids Telegram group chat. Thanks for the support.

**Comment by stewart-codes** [comment] 2024-02-13 17:29
Fixed in this commit https://github.com/abigpotostew/microcosmbot/commit/36c310d4c7fef8494e285b0aea5ff9effa88df12

The issue is that a user, that was previously a member of the chat but then was correctly banned due to transferring their bad kid nft out of the wallet, could not join again because their ban status was preventing them from using a valid invite link after re-verifying the wallet with the bad kid nft on the bot. The issue was fixed by calling the unban TG API before issuing a new invite link.

**Closed as completed by stewart-codes** 2024-02-13 17:29 UTC
